import type { Metadata } from "next";
import "../styles/globals.css";


export const metadata: Metadata = {
    title: "Next",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en">
            <body className="">
                {children}
            </body>
        </html>
    );
}
